### ISSUE TITLE
How long till the script finds a wallet with balance on it

### ISSUE THREAD

**Issue by Kojijeto1** [niyankhadka/crypto-wallet-bruteforce#3]
How long will it take for the script to find a wallet with balance on it? How to withdraw it from there?

**Comment by niyankhadka** [comment]
It depends upon how lucky you are!!! 
If the generated wallet address has balance after some run, then that's early findings otherwise, it might take long time. And if there is any balance on it, you can find the wallet seed phrase on the folder named as 'HasBalance' on this version. You can use it to login on web3 wallets.
